databases:
  - name: askme
    plan: free

services:
  - type: web
    name: mysite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: askme
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    plan: free
